import assert from 'node:assert/strict'
import test from 'node:test'
import { createRng, restoreRng, shuffle } from '../../src/domain/rng.js'

const UINT32_SIZE = 0x100000000
const ITEMS = Object.freeze([0, 1, 2, 3, 4, 5, 6, 7])

// Independently checked with integer arithmetic modulo 2^32, not generated by rng.js.
// Each draw records the unsigned output numerator and the post-draw state.
const VECTORS = [
  {
    seed: 0,
    draws: [
      [1144304738, 1831565813],
      [1416247, 3663131626],
      [958946056, 1199730143],
      [627933444, 3031295956],
      [2007157716, 567894473],
    ],
    permutation: [4, 7, 3, 5, 6, 1, 0, 2],
    shuffledState: 4231026099,
  },
  {
    seed: 1,
    draws: [
      [2693262067, 1831565814],
      [11749833, 3663131627],
      [2265367787, 1199730144],
      [4213581821, 3031295957],
      [4159151403, 567894474],
    ],
    permutation: [2, 1, 6, 7, 4, 3, 0, 5],
    shuffledState: 4231026100,
  },
  {
    seed: 12345,
    draws: [
      [4207900869, 1831578158],
      [1317490944, 3663143971],
      [2079646450, 1199742488],
      [3513001552, 3031308301],
      [2187978186, 567906818],
    ],
    permutation: [3, 0, 1, 5, 4, 6, 2, 7],
    shuffledState: 4231038444,
  },
  {
    seed: 4294967295,
    draws: [
      [3850105811, 1831565812],
      [813802916, 3663131625],
      [3073704848, 1199730142],
      [4054706436, 3031295955],
      [3630262831, 567894472],
    ],
    permutation: [0, 2, 6, 3, 5, 4, 1, 7],
    shuffledState: 4231026098,
  },
]

const INVALID_UINT32 = [
  undefined, null, false, true, '', '12345', NaN, Infinity, -Infinity,
  -1, 0.5, UINT32_SIZE, Number.MAX_SAFE_INTEGER, 1n, Symbol('seed'), [], {},
]

function sequence(rng, length) {
  return Array.from({ length }, () => rng.next())
}

function roundTrip(snapshot) {
  return JSON.parse(JSON.stringify(snapshot))
}

for (const { seed, draws, permutation, shuffledState } of VECTORS) {
  test(`known Mulberry32 sequence and states for seed ${seed}`, () => {
    const rng = createRng(seed)
    assert.deepEqual(rng.snapshot(), { algorithm: 'mulberry32', seed, state: seed })
    for (const [word, state] of draws) {
      const value = rng.next()
      assert.equal(value, word / UINT32_SIZE)
      assert.ok(value >= 0 && value < 1)
      assert.deepEqual(rng.snapshot(), { algorithm: 'mulberry32', seed, state })
    }
  })

  test(`known Fisher–Yates permutation and state for seed ${seed}`, () => {
    const rng = createRng(seed)
    assert.deepEqual(shuffle(ITEMS, rng), permutation)
    assert.deepEqual(rng.snapshot(), {
      algorithm: 'mulberry32', seed, state: shuffledState,
    })
  })

  test(`JSON snapshots restore before and after draws for seed ${seed}`, () => {
    const rng = createRng(seed)
    for (let index = 0; index < draws.length; index += 1) {
      const snapshot = rng.snapshot()
      const serialized = roundTrip(snapshot)
      assert.deepEqual(serialized, snapshot)
      const restored = restoreRng(serialized)
      assert.deepEqual(restored.snapshot(), snapshot)
      assert.equal(restored.next(), draws[index][0] / UINT32_SIZE)
      assert.equal(rng.next(), draws[index][0] / UINT32_SIZE)
      assert.deepEqual(restored.snapshot(), rng.snapshot())
    }
  })
}

test('wraparound to state zero remains restorable without a fallback seed', () => {
  const rng = restoreRng({ algorithm: 'mulberry32', seed: 1, state: 2463401483 })
  assert.equal(rng.next(), 0)
  assert.deepEqual(rng.snapshot(), { algorithm: 'mulberry32', seed: 1, state: 0 })
  const restored = restoreRng(roundTrip(rng.snapshot()))
  assert.equal(restored.next(), 1144304738 / UINT32_SIZE)
  assert.equal(rng.next(), 1144304738 / UINT32_SIZE)
})

test('negative zero is canonicalized to JSON-safe zero', () => {
  assert.deepEqual(createRng(-0).snapshot(), createRng(0).snapshot())
  assert.deepEqual(
    restoreRng({ algorithm: 'mulberry32', seed: -0, state: -0 }).snapshot(),
    roundTrip(createRng(0).snapshot()),
  )
})

test('instances are independent even when draws are interleaved', () => {
  const first = createRng(12345)
  const second = createRng(12345)
  const otherSeed = createRng(1)
  const expected = sequence(first, 100)
  assert.deepEqual(second.snapshot(), createRng(12345).snapshot())
  const actual = Array.from({ length: 100 }, () => {
    otherSeed.next()
    first.next()
    return second.next()
  })
  assert.deepEqual(actual, expected)
})

test('reading, restoring, or modifying snapshots cannot advance or alias an instance', () => {
  const rng = createRng(12345)
  rng.next()
  const saved = rng.snapshot()
  const expected = { ...saved }
  const restored = restoreRng(saved)
  assert.notEqual(rng.snapshot(), saved)
  assert.deepEqual(rng.snapshot(), expected)
  assert.deepEqual(restored.snapshot(), expected)

  saved.algorithm = 'unknown'
  saved.seed = 1
  saved.state = 0
  assert.deepEqual(rng.snapshot(), expected)
  assert.deepEqual(restored.snapshot(), expected)
  assert.equal(rng.next(), 1317490944 / UINT32_SIZE)
  assert.equal(restored.next(), 1317490944 / UINT32_SIZE)
})

test('bounded seeds preserve mixed sequences, shuffles, and resume equivalence', () => {
  const seeds = [
    ...VECTORS.map(({ seed }) => seed), 0x7FFFFFFF, 0x80000000,
    ...Array.from({ length: 32 }, (_, index) => Math.imul(index, 0x9E3779B9) >>> 0),
  ]
  for (const seed of seeds) {
    const uninterrupted = createRng(seed)
    const interrupted = createRng(seed)
    assert.deepEqual(sequence(interrupted, 31), sequence(uninterrupted, 31))
    assert.deepEqual(shuffle(ITEMS, interrupted), shuffle(ITEMS, uninterrupted))
    const resumed = restoreRng(roundTrip(interrupted.snapshot()))
    for (let round = 0; round < 8; round += 1) {
      assert.deepEqual(shuffle(ITEMS, resumed), shuffle(ITEMS, uninterrupted))
      const values = sequence(resumed, 64)
      assert.ok(values.every((value) => value >= 0 && value < 1))
      assert.deepEqual(values, sequence(uninterrupted, 64))
      assert.deepEqual(resumed.snapshot(), uninterrupted.snapshot())
    }
  }
})

test('shuffle makes a shallow copy and preserves element identity and multiplicity', () => {
  const first = Object.freeze({ id: 'first' })
  const second = Object.freeze({ id: 'second' })
  const input = Object.freeze([first, second, first, undefined, null, undefined, 'a', 'a'])
  const shuffled = shuffle(input, createRng(12345))
  assert.notEqual(shuffled, input)
  assert.equal(shuffled.length, input.length)
  assert.deepEqual(input, [first, second, first, undefined, null, undefined, 'a', 'a'])
  for (const value of new Set(input)) {
    assert.equal(
      shuffled.filter((item) => item === value).length,
      input.filter((item) => item === value).length,
    )
  }
})

test('shuffle consumes exactly length minus one draws, including self-swaps', () => {
  for (let length = 0; length <= 52; length += 1) {
    const input = Array.from({ length }, (_, index) => index)
    const rng = createRng(12345)
    const control = createRng(12345)
    const shuffled = shuffle(input, rng)
    sequence(control, Math.max(0, length - 1))
    assert.deepEqual(rng.snapshot(), control.snapshot())
    assert.deepEqual([...shuffled].sort((a, b) => a - b), input)
    assert.notEqual(shuffled, input)
  }

  let calls = 0
  const selfSwaps = {
    next() {
      calls += 1
      return 1 - 1 / UINT32_SIZE
    },
  }
  assert.deepEqual(shuffle(ITEMS, selfSwaps), ITEMS)
  assert.equal(calls, ITEMS.length - 1)
  assert.deepEqual(shuffle([0, 1], { next: () => 0 }), [1, 0])
})

test('empty and singleton shuffles never request a random value', () => {
  const rng = { next: () => assert.fail('Unexpected draw') }
  for (const input of [[], ['only']]) {
    const result = shuffle(input, rng)
    assert.deepEqual(result, input)
    assert.notEqual(result, input)
  }
})

test('invalid seeds are rejected without coercion or implicit defaults', () => {
  assert.throws(() => createRng(), TypeError)
  for (const seed of INVALID_UINT32) {
    assert.throws(() => createRng(seed), {
      name: 'TypeError', message: 'seed must be an unsigned 32-bit integer',
    })
  }
})

test('malformed or unsupported snapshots are rejected without mutating a live RNG', () => {
  const rng = createRng(12345)
  rng.next()
  const valid = rng.snapshot()
  const invalid = [
    undefined, null, false, 12345, '12345', [], () => valid,
    {}, { seed: valid.seed }, { seed: valid.seed, state: valid.state },
    { algorithm: 'mulberry32', seed: valid.seed },
    { algorithm: 'mulberry32', state: valid.state },
    { ...valid, algorithm: undefined },
    { ...valid, algorithm: 'future-rng' },
    { ...valid, algorithm: 'Mulberry32' },
    { ...valid, extra: true },
    Object.create(valid),
    ...INVALID_UINT32.flatMap((value) => [
      { ...valid, seed: value }, { ...valid, state: value },
    ]),
  ]
  for (const snapshot of invalid) {
    assert.throws(() => restoreRng(snapshot), TypeError)
    assert.deepEqual(rng.snapshot(), valid)
  }
  const frozen = Object.freeze({ ...valid })
  assert.deepEqual(restoreRng(frozen).snapshot(), frozen)
})

test('invalid shuffle inputs are rejected before consuming RNG state', () => {
  const rng = createRng(12345)
  const snapshot = rng.snapshot()
  const invalid = [
    undefined, null, false, 2, 'abc', {}, { length: 2, 0: 'a', 1: 'b' },
    new Set(ITEMS), new Uint32Array(ITEMS), Array(2), [0, , 2],
  ]
  for (const input of invalid) {
    assert.throws(() => shuffle(input, rng), TypeError)
    assert.deepEqual(rng.snapshot(), snapshot)
  }
  for (const invalidRng of [undefined, null, false, 1, 'rng', {}, { next: 1 }, () => 0]) {
    for (const input of [[], ['only'], ITEMS]) {
      assert.throws(() => shuffle(input, invalidRng), TypeError)
    }
  }
})

test('shuffle rejects invalid RNG outputs before calculating a target', () => {
  const input = [0, 1]
  const invalid = [undefined, null, false, '0.5', NaN, Infinity, -Infinity, -0.1, 1, 1.1]
  for (const value of invalid) {
    assert.throws(() => shuffle(input, { next: () => value }), {
      name: 'TypeError', message: 'RNG next() must return a finite number in [0, 1)',
    })
    assert.deepEqual(input, [0, 1])
  }
})

test('module initialization, generation, restoration, and shuffle never use Math.random', async (t) => {
  t.mock.method(Math, 'random', () => assert.fail('Hidden Math.random use'))
  const isolated = await import('../../src/domain/rng.js?no-hidden-randomness')
  const rng = isolated.createRng(12345)
  assert.deepEqual(isolated.shuffle(ITEMS, rng), VECTORS[2].permutation)
  const restored = isolated.restoreRng(roundTrip(rng.snapshot()))
  assert.deepEqual(sequence(restored, 20), sequence(rng, 20))
  assert.deepEqual(restored.snapshot(), rng.snapshot())
})
